export const ACTION_CONSTANTS = {
    ADD_TODOS: 'ADD_TODOS',
    DELETE_TODOS: 'DELETE_TODOS',
    COMPLETE_TODOS: 'COMPLETE_TODOS',
    UNCOMPLETE_TODOS: 'UNCOMPLETE_TODOS',
    ADD_BULK_TODOS: 'ADD_BULK_TODOS'
}